### ISSUE TITLE
Helper method to get all nodes and edges

### ISSUE THREAD

**Issue by mfenner** [ropensci/ghql#16]
One use case for GraphQL is visualizing the underlying graph, and this is typically done by extracting all the nodes and edges and then using a package such as `igraph`. While this can be done with standard R methods (see my attempts for example [here](https://github.com/datacite/notebooks/blob/master/pid-graph/r-researcher-publications.ipynb)), but this could maybe also done by helper methods provided by `ghql`. Would that be useful?

**Comment by sckott** [comment]
That sounds good, except I would want to avoid introducing heavy dependencies such as dplyr. Could it be done without dplyr?

**Comment by mfenner** [comment]
I need to investigate more.

**Comment by sckott** [comment]
sounds good

**Comment by mpadge** [comment]
@mfenner I've taken over maintenance of this package from Scott, and am going to close this issue now. Queries can of course be arbitrarily constructed to extract details of nodes and edges, but notions of "all" nodes and edges are always context dependent and so have to be constructed for each case anyway. I'm going to close this now.
