### ISSUE TITLE
How to use R variable in query call 

### ISSUE THREAD

**Issue by kyleweise-pi** [ropensci/ghql#17]
I am attempting to query a GraphQL API using a non-hard-coded ID. My code is
```
library(ghql)
library(jsonlite)
library(httr)


client <- GraphqlClient$new(url = "http://genetics-api.opentargets.io/graphql")

qry <- Query$new()

qry$query('query', '
          {
            geneInfo(geneId: "ENSG00000137033") {
            id
            symbol
            chromosome
            start
            end
            bioType
            __typename
            }
          }')





responses <- client$exec(qry$queries$query)
```

Which works fine. When the ID is given to `qry$query()` in a non-hard-coded way:

```
test_gene <- 'ENSG00000137033'

test_query <- paste0(
'{
  geneInfo(geneId: "', test_gene, '") {
    id
    symbol
    chromosome
    start
    end
    bioType
    __typename
  }
}')


qry$query(paste0('query', test_query))
```

it breaks. I get the error:
` Error in make_query(x) : argument "x" is missing, with no default`

There must be a way around this, what am I missing?

Thanks!

-Kyle

**Comment by kyleweise-pi** [comment]
So I have this [working in the Open Targets GraphiQL browser](http://genetics-api.opentargets.io/graphql/browser?query=query%20GetGeneInfo(%24gene_to_search%3A%20String!)%20%7B%0A%20%20studiesAndLeadVariantsForGene(geneId%3A%20%24gene_to_search)%20%7B%0A%20%20%20%20indexVariant%20%7B%0A%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20study%20%7B%0A%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20traitReported%0A%20%20%20%20%20%20pubAuthor%0A%20%20%20%20%20%20pubDate%0A%20%20%20%20%20%20pmid%0A%20%20%20%20%20%20nInitial%0A%20%20%20%20%20%20nReplication%0A%20%20%20%20%20%20nCases%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20pval%0A%20%20%20%20oddsRatio%0A%20%20%20%20oddsRatioCILower%0A%20%20%20%20oddsRatioCIUpper%0A%20%20%20%20beta%0A%20%20%20%20betaCILower%0A%20%20%20%20betaCIUpper%0A%20%20%20%20direction%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A&operationName=GetGeneInfo&variables=%7B%0A%20%20%22gene_to_search%22%3A%20%22ENSG00000137033%22%0A%7D), but how to format this in `ghql` to be able to use in `qry$query(...)` ?

**Comment by sckott** [comment]
thanks for your question @kyleweise-pi - having a look

**Comment by sckott** [comment]
the `argument x is missing` error is because you want `qry$query("query", test_query)` instead of `qry$query(paste0('query', test_query))` (which passes only 1 thing to `qry$query()`, whereas 2 things are required. and since you passed them positionally without using the param names, the character string gets passed to the first parameter, and the second (`x`) is then missing

**Comment by kyleweise-pi** [comment]
Thank you @sckott , I figured it was something silly like this. Just tried with your correction and everything works perfectly. Appreciate the help and the package!

**Comment by sckott** [comment]
glad it works!
