### ISSUE TITLE
Error: Invalid Token

### ISSUE THREAD

**Issue by TimBMK** [ropensci/ghql#24]
I'm looking to establish a connection between R and a GraphQL Database via ghql, but the authorization is failing and I'm not sure why. 

For 
```
conn <- GraphqlClient$new(url = link, 
                          headers = list(Authorization = paste0("Bearer ", token)))

conn$ping()
```

I get a 
```
Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid.
```

When accessing the GraphQL database's visual interface, however, the token is working just fine when used in the request header as 

```
{
"Authorization": "Bearer -token-"
}

```

Changing the header structure or content throws the same error, so I'm suspecting the problem is not with the actual token, but the data structure or maybe its encoding? But I'm not sure why I'm getting the error, and from curl specifically. Any help appreciated.

I'm running curl 4.3 and ghql 0.1.0 under R 4.0.3

**Comment by sckott** [comment]
thanks. probably a curl (not the R pkg, the c library) or openssl/etc. issue

Share you R session info

**Comment by sckott** [comment]
and what does `curl::curl_version()` output

**Comment by TimBMK** [comment]
```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.2    jsonlite_1.7.1 ghql_0.1.0    

loaded via a namespace (and not attached):
 [1] graphql_1.5      Rcpp_1.0.5       crayon_1.3.4     crul_1.0.0       R6_2.5.0         lifecycle_0.2.0  magrittr_2.0.1   pillar_1.4.7     rlang_0.4.8     
[10] curl_4.3         rstudioapi_0.13  ellipsis_0.3.1   vctrs_0.3.4      generics_0.1.0   tools_4.0.3      glue_1.4.2       purrr_0.3.4      compiler_4.0.3  
[19] pkgconfig_2.0.3  elastic_1.1.0    tidyselect_1.1.0 tibble_3.0.4     httpcode_0.3.0 
```


```
> curl::curl_version()
$version
[1] "7.64.1"

$ssl_version
[1] "(OpenSSL/1.1.1a) Schannel"

$libz_version
[1] "1.2.11"

$libssh_version
[1] "libssh2/1.8.2"

$libidn_version
[1] NA

$host
[1] "x86_64-w64-mingw32"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps"  "ldap"   "ldaps"  "pop3"   "pop3s"  "rtsp"   "scp"    "sftp"   "smtp"   "smtps" 
[19] "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] FALSE

$idn
[1] TRUE

```

**Comment by TimBMK** [comment]
An important information may also be that I'm accessing GraphQL via a tunnel, so the link to the API is based on a local host:

```
link <- "https://127.0.0.1:5001/graphql"

conn <- GraphqlClient$new(url = link, 
                          headers = list(Authorization = paste0("Bearer ", token)))
```

**Comment by sckott** [comment]
perhaps this is a possible solution. https://github.com/ropensci/weathercan/issues/104#issuecomment-716614526 I don't think it would apply here since you don't have windows 7. 

I'm guessing your running a graphql server locally. If it's easy to setup a hello world i can do the same and test it out

**Comment by TimBMK** [comment]
The graphql is runnning on a server and is only accessible through a jump server, hence the tunnel (through a VPN) as a shortcut. Unfortunately, I'm not an admin there and can't easily set up a test environment for you. 

I'm thinking it may have something to do with the data the server expects for authentication or the endpoint itself. I'll tinker with that a bit and see. Otherwise, I'll probably have to check if that curl version has issues with the specific infrastructure of the server. If you can think of something else to troubleshoot, let me know.

**Comment by sckott** [comment]
Can you connect successfully to the graphql server without this pkg? e.g., 

```r
url <- "https://127.0.0.1:5001/graphql"
crul::HttpClient$new(url, headers = list(Authorization = paste0("Bearer ", token)))$get()
```

**Comment by TimBMK** [comment]
Establishing the connection with crul yields the same error as with ghql (SEC_E_INVALID_TOKEN). 

I've found out that the webtoken is expected in json by the server. Maybe that's something that needs to be specified in the call?

**Comment by sckott** [comment]
Okay, i assume by json you mean not as a header, but rather in the body of the request? Can you show me what that looks like in a curl request or docs or something

**Comment by TimBMK** [comment]
According to what I found out, a typical request would be in the format of 
`curl -H ‘Accept: application/json’ -H “Authorization: Bearer ${TOKEN}” https://{hostname}/graphql`
If you need more information, I can reach out to the admins.

However, when using the graphiQL (the graphical interface), sending the token in the form of 
`"Authorization" : "Bearer TOKEN" `
as a _Request Header_ works fine. Hence I assumed it would be a header for the call via R, too.

**Comment by sckott** [comment]
> `curl -H ‘Accept: application/json’ -H “Authorization: Bearer ${TOKEN}” https://{hostname}/graphql`

That's how it works in ghql. The json part there is just saying that you want JSON back in the response - doesn't have anything to do with the authorization.

**Comment by TimBMK** [comment]
Right, makes sense. 

Since it doesn't seem to be an issue with your package, but rather with either curl or the server infrastructure, I'll get in touch with the admins and see if they can help.

Thank you so much for your time, I appreciate it!

**Comment by sckott** [comment]
hope it gets solved ASAP :)

**Comment by TimBMK** [comment]
Well, after some long testing sessions and throwing numerous versions of curl requests both via cmd and R, it turned out that... *damdam* https was the problem. Replacing https with http in the link resolved the issue. I'm surprised I didn't get a more precise error for that, but well. Check your urls first, folks! 

Now I'm running into some problems trying to get the token via R and crul, as the POST format doesn't seem to add up to what graphQL is expecting. But I'll ask that question over there :)

**Comment by sckott** [comment]
Yeah, there doesn't seem to be good error messages for http vs. https
