### ISSUE TITLE
How does ghql compare to graphql?

### ISSUE THREAD

**Issue by maelle** [ropensci/ghql#9]
Just curious :-)

graphql https://github.com/ropensci/graphql developed by @jeroen 

Plus there's https://github.com/schloerke/gqlr (and maybe other?)

**Comment by maelle** [comment]
I think I got it but it might be good to write a link to each of them in the respective docs (well one of them doesn't even have a README :joy:)

**Comment by sckott** [comment]
yes, good idea to add mention of the two other pkgs in README here, can you send PR?

**Comment by maelle** [comment]
I will when I get my use case ready (and thus my ideas clear) 😁

**Comment by sckott** [comment]
fixed in #13
